AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  URL Shortener Service
  Simplified AWS SAM template for local and regional use.
  Two Lambda functions (shorten & redirect) behind an API Gateway,
  plus a lightweight S3-hosted frontend (no CloudFront).

Parameters:
  AppEnv:
    Type: String
    AllowedValues:
      - local
      - dev
      - staging
      - prod
    Default: local
    Description: Application environment

  AppName:
    Type: String
    Default: cloudshortener
    Description: Application name

  FrontendBucketName:
    Type: String
    Default: "cloudshortener-frontend"
    Description: S3 bucket for hosting the frontend

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
    Runtime: python3.13
    Architectures:
      - arm64
    Environment:
      Variables:
        APP_ENV: !Ref AppEnv
        APP_NAME: !Ref AppName
        PROJECT_ROOT: "/var/task"
        USER_POOL_ID: !Ref CognitoUserPool
        USER_POOL_CLIENT_ID: !Ref CognitoUserPoolClient
  Api:
    TracingEnabled: true
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Authorization,Content-Type'"
      AllowOrigin: "'*'"

Resources:

  ##################################################
  # Cognito User Pool + Client
  ##################################################
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AppName}-${AppEnv}-users"
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          Required: true
          Mutable: false
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireUppercase: false
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: !Sub "${AppName}-${AppEnv}-web"
      GenerateSecret: false
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - openid
        - email
        - profile
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - "http://localhost:3000/"   # adjust for your frontend
      LogoutURLs:
        - "http://localhost:3000/"

  ##################################################
  # Explicit API with Cognito Authorizer
  ##################################################
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref AppEnv
      TracingEnabled: true
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Authorization,Content-Type'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt CognitoUserPool.Arn
        DefaultAuthorizer: CognitoAuthorizer

  ##################################################
  # Lambda: Shorten URL (protected)
  ##################################################
  ShortenUrlFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: python3.13
      BuildProperties:
        Include:
          - cloudshortener/**
          - config/shorten_url/**
    Properties:
      FunctionName: shorten-url-function
      CodeUri: .
      Handler: cloudshortener.lambdas.shorten_url.app.lambda_handler
      Events:
        ShortenUrlApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /v1/shorten
            Method: post

  ##################################################
  # Lambda: Redirect URL (public)
  ##################################################
  RedirectUrlFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: python3.13
      BuildProperties:
        Include:
          - cloudshortener/**
          - config/redirect_url/**
    Properties:
      FunctionName: redirect-url-function
      CodeUri: .
      Handler: cloudshortener.lambdas.redirect_url.app.lambda_handler
      Events:
        RedirectUrlApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{shortcode}
            Method: get
            Auth:
              Authorizer: NONE

  ##################################################
  # Application Insights & Monitoring
  ##################################################
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: true

  ##################################################
  # FrontEnd (S3 Static Website Hosting)
  ##################################################
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${FrontendBucketName}-${AWS::AccountId}-${AWS::Region}"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false   # allow policy-based public read
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowPublicRead
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${FrontendBucket.Arn}/*"

Outputs:
  ##################################################
  # Outputs for convenience
  ##################################################
  ApiUrl:
    Description: Base URL for the API Gateway
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${AppEnv}/

  FrontendUrl:
    Description: Public S3 website URL for the frontend
    Value: !GetAtt FrontendBucket.WebsiteURL

  ShortenUrlFunctionArn:
    Description: ARN of the Shorten URL Lambda Function
    Value: !GetAtt ShortenUrlFunction.Arn

  RedirectUrlFunctionArn:
    Description: ARN of the Redirect URL Lambda Function
    Value: !GetAtt RedirectUrlFunction.Arn

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool

  UserPoolClientId:
    Description: Cognito App Client ID
    Value: !Ref CognitoUserPoolClient
