AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  URL Shortener Service
  Simplified AWS SAM template for local and regional use.
  Two Lambda functions (shorten & redirect) behind an API Gateway,
  plus a lightweight S3-hosted frontend (no CloudFront).

Parameters:
  AppEnv:
    Type: String
    AllowedValues:
      - local
      - dev
      - staging
      - prod
    Default: local
    Description: Application environment

  AppName:
    Type: String
    Default: cloudshortener
    Description: Application name

  FrontendBucketName:
    Type: String
    Default: cloudshortener-frontend
    Description: S3 bucket for hosting the frontend

  AppConfigAgentURL:
    Type: String
    Default: 'n/a'
    NoEcho: true
    Description: AppConfig agent URL for the backend

Conditions:
  IsLocal:
    Fn::Equals:
      - !Ref AppEnv
      - "local"

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
    Runtime: python3.13
    Architectures:
      - arm64
    Environment:
      Variables:
        APP_ENV: !Ref AppEnv
        APP_NAME: !Ref AppName
        PROJECT_ROOT: /var/task
        # TODO: move out cognito user environment variables only to shortenURLbackend
        USER_POOL_ID: !Ref CognitoUserPool
        USER_POOL_CLIENT_ID: !Ref CognitoUserPoolClient
        APPCONFIG_APP_ID: !Ref AppConfigApplication
        APPCONFIG_ENV_ID: !Ref AppConfigEnvironment
        APPCONFIG_PROFILE_ID: !Ref BackendConfigProfile
        APPCONFIG_AGENT_URL: !If
          - IsLocal
          - !Ref AppConfigAgentURL
          - !Ref AWS::NoValue
  Api:
    TracingEnabled: true
    Cors:
      AllowMethods: '''GET,POST,OPTIONS'''
      AllowHeaders: '''Authorization,Content-Type'''
      AllowOrigin: '''*'''

Resources:
  ##################################################
  # AppConfig
  ##################################################
  AppConfigApplication:
    Type: AWS::AppConfig::Application
    Properties:
      Name: !Sub ${AppName}

  AppConfigEnvironment:
    Type: AWS::AppConfig::Environment
    Properties:
      ApplicationId: !Ref AppConfigApplication
      Name: !Ref AppEnv

  BackendConfigProfile:
    Type: AWS::AppConfig::ConfigurationProfile
    Properties:
      ApplicationId: !Ref AppConfigApplication
      Name: backend-config
      LocationUri: hosted # using AppConfig hosted store
      Type: AWS.Freeform
      # Optional: add a JSON schema validator later
  
    # Create a hosted configuration version with inline JSON
  BackendHostedConfigVersion:
    Type: AWS::AppConfig::HostedConfigurationVersion
    Properties:
      ApplicationId: !Ref AppConfigApplication
      ConfigurationProfileId: !Ref BackendConfigProfile
      ContentType: application/json
      # Keep placeholders literal; do NOT wrap with !Sub
      Content: !Sub |
        {
          "active_backend": "redis",
          "configs": {
            "shorten_url": {
              "redis": {
                "host": "{{resolve:ssm:/${AppName}/${AppEnv}/shorten_url/redis/host}}",
                "port": {{resolve:ssm:/${AppName}/${AppEnv}/shorten_url/redis/port}},
                "db":   {{resolve:ssm:/${AppName}/${AppEnv}/shorten_url/redis/db}},
                "username": "{{resolve:secretsmanager:${AppName}/${AppEnv}/shorten_url/redis:SecretString:username}}",
                "password": "{{resolve:secretsmanager:${AppName}/${AppEnv}/shorten_url/redis:SecretString:password}}"
              }
            },
            "redirect_url": {
              "redis": {
                "host": "{{resolve:ssm:/${AppName}/${AppEnv}/redirect_url/redis/host}}",
                "port": {{resolve:ssm:/${AppName}/${AppEnv}/redirect_url/redis/port}},
                "db":   {{resolve:ssm:/${AppName}/${AppEnv}/redirect_url/redis/db}},
                "username": "{{resolve:secretsmanager:${AppName}/${AppEnv}/redirect_url/redis:SecretString:username}}",
                "password": "{{resolve:secretsmanager:${AppName}/${AppEnv}/redirect_url/redis:SecretString:password}}"
              }
            }
          }
        }

  # Deploy the hosted configuration version
  BackendConfigDeployment:
    Type: AWS::AppConfig::Deployment
    Properties:
      ApplicationId: !Ref AppConfigApplication
      EnvironmentId: !Ref AppConfigEnvironment
      ConfigurationProfileId: !Ref BackendConfigProfile
      ConfigurationVersion: !GetAtt BackendHostedConfigVersion.VersionNumber
      DeploymentStrategyId: AppConfig.AllAtOnce
      Description: Deploy backend config

  ##################################################
  # Cognito User Pool + Client
  ##################################################
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${AppName}-${AppEnv}-users
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          Required: true
          Mutable: false
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireUppercase: false
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref CognitoUserPool
      Domain: !Sub ${AppName}-${AppEnv}

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: !Sub ${AppName}-${AppEnv}-web
      GenerateSecret: false
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
        - email
        - profile
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - !Sub https://${CloudFrontDistribution.DomainName}
        - !Sub https://${CloudFrontDistribution.DomainName}/
      LogoutURLs:
        - !Sub https://${CloudFrontDistribution.DomainName}
        - !Sub https://${CloudFrontDistribution.DomainName}/
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      TokenValidityUnits:
        IdToken: days
        AccessToken: days
        RefreshToken: days
      IdTokenValidity: 1
      AccessTokenValidity: 1
      RefreshTokenValidity: 30

  ##################################################
  # Explicit API with Cognito Authorizer
  ##################################################
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref AppEnv
      TracingEnabled: true
      Cors:
        AllowMethods: '''GET,POST,OPTIONS'''
        AllowHeaders: '''Authorization,Content-Type'''
        AllowOrigin: '''*'''
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt CognitoUserPool.Arn
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false

  ##################################################
  # Lambda: Common IAM Role
  ##################################################
  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaFunctionAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - appconfig:StartConfigurationSession
                  - appconfig:GetLatestConfiguration
                Resource: '*'
              - Effect: Allow
                Action:
                  - ssm:GetParameter*
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AppName}/${AppEnv}/*
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${AppName}/${AppEnv}/*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                Resource: "*"

  ##################################################
  # Lambda: Shorten URL (protected)
  ##################################################
  ShortenUrlFunction:
    Type: AWS::Serverless::Function
    # TODO: remove if fetching is successful
    Metadata:
      BuildMethod: python3.13
      BuildProperties:
        Include:
          - cloudshortener/**
          - config/shorten_url/**
    Properties:
      FunctionName: shorten-url-function
      CodeUri: .
      Handler: cloudshortener.lambdas.shorten_url.app.lambda_handler
      Role: !GetAtt LambdaFunctionRole.Arn
      Events:
        ShortenUrlApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /v1/shorten
            Method: post

  ##################################################
  # Lambda: Redirect URL (public)
  ##################################################
  RedirectUrlFunction:
    Type: AWS::Serverless::Function
    # TODO: remove if fetching is successful
    Metadata:
      BuildMethod: python3.13
      BuildProperties:
        Include:
          - cloudshortener/**
          - config/redirect_url/**
    Properties:
      FunctionName: redirect-url-function
      CodeUri: .
      Handler: cloudshortener.lambdas.redirect_url.app.lambda_handler
      Role: !GetAtt LambdaFunctionRole.Arn
      Events:
        RedirectUrlApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{shortcode}
            Method: get
            Auth:
              Authorizer: NONE

  ##################################################
  # Application Insights & Monitoring
  ##################################################
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: true

  ##################################################
  # FrontEnd (S3 Static Website Hosting)
  ##################################################
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${FrontendBucketName}-${AppEnv}-${AWS::AccountId}-${AWS::Region}
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false # allow policy-based public read
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontAccess
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub ${FrontendBucket.Arn}/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}

  ##################################################
  # CloudFront Distribution for HTTPS
  ##################################################
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !Ref OriginAccessControl
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # Managed-CachingOptimized
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: PriceClass_100
        Comment: Regional distribution for Bulgaria/Europe
        HttpVersion: http2
        IPV6Enabled: false

  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub ${AppName}-${AppEnv}-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

Outputs:
  ##################################################
  # Outputs for convenience
  ##################################################
  ApiUrl:
    Description: Base URL for the API Gateway
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${AppEnv}/

  FrontendUrl:
    Description: HTTPS CloudFront URL for the frontend
    Value: !Sub https://${CloudFrontDistribution.DomainName}

  FrontendBucketName:
    Description: S3 bucket name, hosting frontend application
    Value: !Ref FrontendBucket

  RedirectUrlFunctionArn:
    Description: ARN of the Redirect URL Lambda Function
    Value: !GetAtt RedirectUrlFunction.Arn

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool

  UserPoolClientId:
    Description: Cognito App Client ID
    Value: !Ref CognitoUserPoolClient

  CognitoHostedUIUrl:
    Description: Cognito Hosted UI Login URL
    Value: !Sub https://${CognitoUserPoolDomain}.auth.${AWS::Region}.amazoncognito.com/login?client_id=${CognitoUserPoolClient}&response_type=code&scope=openid+email+profile&redirect_uri=https://${CloudFrontDistribution.DomainName}/

  CognitoHostedUIDomain:
    Description: Cognito Hosted UI Domain
    Value: !Sub ${CognitoUserPoolDomain}.auth.${AWS::Region}.amazoncognito.com

  CloudFrontDistributionId:
    Description: CloudFront Distribution ID (for cache invalidation)
    Value: !Ref CloudFrontDistribution

  AppConfigApplicationId:
    Description: AppConfig Application ID
    Value: !Ref AppConfigApplication

  AppConfigEnvironmentId:
    Description: AppConfig Environment ID
    Value: !Ref AppConfigEnvironment

  BackendConfigProfileId:
    Description: AppConfig Configuration Profile ID
    Value: !Ref BackendConfigProfile