AWSTemplateFormatVersion: '2010-09-09'
Description: |
  CloudShortener - Frontend Stack
  S3 bucket for static hosting and CloudFront distribution.

Parameters:
  AppName:
    Type: String
    Default: cloudshortener
    Description: Application name

  AppEnv:
    Type: String
    AllowedValues:
      - local
      - dev
      - staging
      - prod
    Default: local
    Description: Application environment

  FrontendBucketName:
    Type: String
    Default: cloudshortener-frontend
    Description: S3 bucket name prefix for hosting the frontend

Resources:
  ##################################################
  # FrontEnd (S3 Static Website Hosting)
  ##################################################
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${FrontendBucketName}-${AppEnv}-${AWS::AccountId}-${AWS::Region}
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false # allow policy-based public read
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontAccess
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub ${FrontendBucket.Arn}/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}

  ##################################################
  # CloudFront Distribution for HTTPS
  ##################################################
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub ${AppName}-${AppEnv}-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !Ref OriginAccessControl
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # Managed-CachingOptimized
        CustomErrorResponses:
          # Allow access to frontend's auth endpoints (/login, /logout, etc.).
          # Auth endpoints don't exist as files in the S3 bucket, so CloudFront returns 403 Forbidden.
          # We redirect 403/404 to index.html and let the Vue Router handle the routing.
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: PriceClass_100
        Comment: Regional distribution for Bulgaria/Europe
        HttpVersion: http2
        IPV6Enabled: false

Outputs:
  FrontendUrl:
    Description: HTTPS CloudFront URL for the frontend
    Value: !Sub https://${CloudFrontDistribution.DomainName}

  FrontendBucketName:
    Description: S3 bucket name hosting frontend application
    Value: !Ref FrontendBucket

  FrontendBucketArn:
    Description: S3 bucket ARN
    Value: !GetAtt FrontendBucket.Arn

  CloudFrontDistributionId:
    Description: CloudFront Distribution ID (for cache invalidation)
    Value: !Ref CloudFrontDistribution

  CloudFrontDomainName:
    Description: CloudFront domain name
    Value: !GetAtt CloudFrontDistribution.DomainName
