# Default short URL TTL duration
ONE_YEAR_SECONDS = 31_536_000  # 60 * 60 * 24 * 365
ONE_MONTH_SECONDS = 2_592_000  # 60 * 60 * 24 * 30

# Default short URL monthly hit quota
DEFAULT_LINK_HITS_QUOTA = 10_000

# Default link generation quota for users
DEFAULT_LINK_GENERATION_QUOTA = 20

# Application: environment variable names
APP_ENV_ENV = 'APP_ENV'
APP_NAME_ENV = 'APP_NAME'
PROJECT_ROOT_ENV = 'PROJECT_ROOT'
AWS_SAM_LOCAL_ENV = 'AWS_SAM_LOCAL'
LOG_LEVEL_ENV = 'LOG_LEVEL'

# AppConfig: environment variable names
APPCONFIG_APP_ID_ENV = 'APPCONFIG_APP_ID'
APPCONFIG_ENV_ID_ENV = 'APPCONFIG_ENV_ID'
APPCONFIG_PROFILE_ID_ENV = 'APPCONFIG_PROFILE_ID'
APPCONFIG_AGENT_URL_ENV = 'APPCONFIG_AGENT_URL'
APPCONFIG_PROFILE_NAME_ENV = 'APPCONFIG_PROFILE_NAME'

# ElastiCache: SSM parameter paths for ElastiCache connection details
ELASTICACHE_HOST_PARAM_ENV = 'ELASTICACHE_HOST_PARAM'
ELASTICACHE_PORT_PARAM_ENV = 'ELASTICACHE_PORT_PARAM'
ELASTICACHE_DB_PARAM_ENV = 'ELASTICACHE_DB_PARAM'
ELASTICACHE_USER_PARAM_ENV = 'ELASTICACHE_USER_PARAM'  # optional

# ElastiCache: Secrets Manager name holding credentials JSON: {"username": "...", "password": "..."}
ELASTICACHE_SECRET_ENV = 'ELASTICACHE_SECRET'  # noqa: S105

# LocalStack: endpoint URL environment variable for local development
LOCALSTACK_ENDPOINT_ENV = 'LOCALSTACK_ENDPOINT'
