"""Cache key schema utility for consistent key naming in cache DAO operations.

This module provides a lightweight key schema class for generating
predictable, namespaced cache keys used by data access objects (DAOs)
that manage cached application configuration.

Responsibilities:
    - Define consistent key formats for AppConfig cache keys.
    - Optionally prepend a namespace prefix for environment separation.

Classes:
    CacheKeySchema:
        Provides methods for generating AppConfig-related cache keys
        (e.g., latest pointer, versioned blobs, and metadata) with optional
        application-level prefixing for namespace isolation.

Functions:
    prefix_key(func):
        Internal decorator used to automatically prepend a configured prefix
        to generated cache keys.
        NOTE: Do NOT import or use this decorator directly. It's intended only
              for internal use within CacheKeySchema's implementation.

Example:
    >>> keys = CacheKeySchema(prefix="cloudshortener:dev")
    >>> keys.appconfig_latest_key()
    'cloudshortener:dev:appconfig:latest'
    >>> keys.appconfig_version_key(12)
    'cloudshortener:dev:appconfig:v12'
    >>> keys.appconfig_metadata_key(12)
    'cloudshortener:dev:appconfig:v12:metadata'

TODO:
    - Add helper method to automatically generate prefix from config/environment.

NOTE: Yes, this class mirrors RedisKeySchema, but we don't want to spaghettify the caching layer with our Redis datastore backend.
"""

from typing import Optional


__all__ = ['CacheKeySchema']  # hide internal decorator prefix_key from imports


def prefix_key(func: callable) -> callable:
    """Decorator that prefixes cache keys generated by CacheKeySchema methods.

    NOTE: Do NOT import or use this decorator. It's intended only for internal
          use within CacheKeySchema's implementation.

    Args:
        func (callable):
            A CacheKeySchema method that returns a cache key string.

    Returns:
        callable:
            A wrapped function that prefixes the generated key with the
            configured prefix (if provided).

    Example:
        >>> class CacheKeySchema:
        ...     @prefix_key
        ...     def appconfig_latest_key(self) -> str:
        ...         return "appconfig:latest"
        ...
        >>> schema = CacheKeySchema(prefix="app")
        >>> schema.appconfig_latest_key()
        'app:appconfig:latest'
    """

    def wrapper(self, *args, **kwargs) -> str:
        key = func(self, *args, **kwargs)
        return f'{self.prefix}:{key}' if self.prefix is not None else key

    return wrapper


class CacheKeySchema:
    """Provide standardized cache keys for storing AppConfig in a cache backend.

    An optional prefix can be provided to namespace all generated keys.
    It is highly encouranged to set a custom prefix for each app and environment,
    e.g. "cloudshortener:prod" or "cloudshortener:dev".

    Attributes:
        prefix (Optional[str]):
            Optional string prefix to prepend to all generated keys.

    Methods:
        appconfig_latest_key() -> str:
            Generate the pointer key that refers to the latest AppConfig version.

        appconfig_version_key(version: int) -> str:
            Generate the key holding the serialized AppConfig for a given version.

        appconfig_metadata_key(version: int) -> str:
            Generate the key holding metadata for a given AppConfig version.

    Example:
        >>> schema = CacheKeySchema(prefix="shortener")
        >>> schema.appconfig_latest_key()
        'shortener:appconfig:latest'
        >>> schema.appconfig_version_key(5)
        'shortener:appconfig:v5'
        >>> schema.appconfig_metadata_key(5)
        'shortener:appconfig:v5:metadata'

    TODO:
        - Add helper method to automatically generate prefix from config/environment.
    """

    def __init__(self, prefix: Optional[str] = None):
        """Initialize a CacheKeySchema instance.

        Args:
            prefix (Optional[str]):
                Optional string used as a prefix for all generated keys.

        Raises:
            TypeError:
                If the provided prefix is not a string.
        """
        if prefix is not None and not isinstance(prefix, str):
            raise TypeError(f'Prefix must be of type string (given type: {type(prefix)}).')

        self.prefix = f'cache:{prefix}' if prefix is not None else None

    @prefix_key
    def appconfig_latest_key(self) -> str:
        """Generate the cache key for the AppConfig latest version pointer.

        Returns:
            str: A cache key string pointing to the latest AppConfig version, e.g. "appconfig:latest".

        Example:
            >>> CacheKeySchema().appconfig_latest_key()
            'appconfig:latest'
        """
        return 'appconfig:latest'

    @prefix_key
    def appconfig_version_key(self, version: int) -> str:
        """Generate the cache key for a specific AppConfig version blob.

        Args:
            version (int):
                The AppConfig deployment/version number.

        Returns:
            str: A cache key string for the versioned AppConfig, e.g. "appconfig:v12".

        Raises:
            ValueError:
                If the provided version cannot be converted to an integer.

        Example:
            >>> CacheKeySchema().appconfig_version_key(12)
            'appconfig:v12'
        """
        return f'appconfig:v{int(version)}'

    @prefix_key
    def appconfig_metadata_key(self, version: int) -> str:
        """Generate the cache key for metadata of a specific AppConfig version.

        Args:
            version (int):
                The AppConfig deployment/version number.

        Returns:
            str: A cache key string for the version's metadata, e.g. "appconfig:v12:metadata".

        Raises:
            ValueError:
                If the provided version cannot be converted to an integer.

        Example:
            >>> CacheKeySchema().appconfig_metadata_key(12)
            'appconfig:v12:metadata'
        """
        return f'appconfig:v{int(version)}:metadata'
