# Events emitted by the lambda function
MISSING_USER_ID = 'MISSING_USER_ID'
LINK_QUOTA_EXCEEDED = 'LINK_QUOTA_EXCEEDED'
INVALID_JSON = 'INVALID_JSON'
MISSING_TARGET_URL = 'MISSING_TARGET_URL'
SHORT_URL_ALREADY_EXISTS = 'SHORT_URL_ALREADY_EXISTS'
SHORTENING_SUCCESS = 'SHORTENING_SUCCESS'
