# Events emitted by the lambda function
REDIRECT_SUCCESS = 'REDIRECT_SUCCESS'
MISSING_SHORTCODE = 'MISSING_SHORTCODE'
SHORT_URL_NOT_FOUND = 'SHORT_URL_NOT_FOUND'
LINK_QUOTA_EXCEEDED = 'LINK_QUOTA_EXCEEDED'
